version: "3"

services:
  web:
    container_name: web
    build: ./docker/nginx
    networks:
      - whitenetwork
    volumes:
      - static_data:/usr/src/whitenet/static
    ports:
      - 80:80
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/python/dev.Dockerfile
    networks:
      - whitenetwork
    volumes:
      - static_data:/opt/whitenet/web/static
    expose:
      - "8000"
    #    command: ["python", "manage.py", "runserver",  "0.0.0.0:8000"]
    command: ["gunicorn", "app.wsgi:application", "-b", "0.0.0.0:8000"]
    env_file:
      - app/.docker.env
    depends_on:
      - db
      - rabbitmq

  db:
    image: mdillon/postgis:11-alpine
    container_name: db
    networks:
      - whitenetwork
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    env_file:
      - .env.db.dev


  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    networks:
      - whitenetwork
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  db-data:
    driver: local
  static_data:

networks:
  whitenetwork:
    driver: bridge