version: "2.4"

services:
  web:
    container_name: web
    build: ./docker/nginx
    networks:
      - gonm_network
    volumes:
      - static_data:/usr/src/gonm/static
    ports:
      - 80:80
    depends_on:
      app:
        condition: service_healthy

  app:
    #    container_name: app
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    networks:
      - gonm_network
    volumes:
      - static_data:/opt/whitenet/web/static
    expose:
      - "8000"
    command: ["gunicorn", "app.wsgi:application", "-w", "4", "-b", "0.0.0.0:8000"]
    healthcheck:
      test: curl --fail -s http://localhost:8000/ping/ || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 3s
    env_file:
      - app/.prod.env
    depends_on:
      - db

  db:
    image: mdillon/postgis:11-alpine
    container_name: db
    networks:
      - gonm_network
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    env_file:
      - .env.db.prod

volumes:
  db-data:
    driver: local
  static_data:

networks:
  gonm_network:
    driver: bridge