version: "3"

services:
  web:
    container_name: web
    build: ./docker/nginx
    networks:
      - whitenetwork
    volumes:
      - static_data:/usr/src/whitenet/static
    ports:
      - 80:80
    depends_on:
      - app

  app:
    #    container_name: app
    build:
      context: .
      dockerfile: docker/python/prod.Dockerfile
    networks:
      - whitenetwork
    volumes:
      - static_data:/opt/whitenet/web/static
    expose:
      - "8000"
    command: ["gunicorn", "app.wsgi:application", "-w", "4", "-b", "0.0.0.0:8000"]
    env_file:
      - app/.prod.env
    depends_on:
      - db

  db:
    image: mdillon/postgis:11-alpine
    container_name: db
    networks:
      - whitenetwork
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    env_file:
      - .env.db.prod

volumes:
  db-data:
    driver: local
  static_data:

networks:
  whitenetwork:
    driver: bridge